server:
  port: 1111
spring:
  profiles:
    active: peer1
eureka:
  instance:
    hostname: peer1
  client:
    #registerWithEureka: true #代表不向注册中心注册自己
    #fetchRegistry: true #由于注册中心的职责就是维护服务实例，它并不需要去检索服务， 所以也设置为 false
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/
