spring:
  profiles:
    active: test
  application:
    name: eureka-client
---
spring:
  profiles: test
server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/
spring:
  application:
    name: eureka-client
---
spring:
  profiles: dev
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/
spring:
  application:
    name: eureka-client
