spring:
  profiles:
    active: test
  application:
    name: eureka-client
---
spring:
  profiles: test
  rabbitmq:
    addresses: localhost
    port: 5672
    username: root
    password: root
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/
---
spring:
  profiles: dev
  rabbitmq:
    addresses: localhost
    port: 5672
    username: root
    password: root
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/