spring:
  profiles:
    active: peer1
  application:
    name: eurka-server
---
spring:
  profiles: peer1
server:
  port: 8760
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false #代表不向注册中心注册自己
    fetchRegistry: false #由于注册中心的职责就是维护服务实例，它并不需要去检索服务， 所以也设置为 false
    serviceUrl:
       defaultZone: http://peer2:8761/eureka/
---
spring:
  profiles: peer2
server:
  port: 8761
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false #代表不向注册中心注册自己
    fetchRegistry: false #由于注册中心的职责就是维护服务实例，它并不需要去检索服务， 所以也设置为 false
    service-url:
      defaultZone: http://peer1:8760/eureka/
