spring:
  profiles:
    active: test
  application:
    name: eureka-feign
---
spring:
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://wangtao:123456@peer2:8761/eureka
feign:
  hystrix:
    enabled: true #开启熔断器
---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://wangtao:123456@peer2:8761/eureka
feign:
  hystrix:
    enabled: true #开启熔断器

