spring:
  profiles:
    active: test
---
spring:
  profiles: test
  application:
      name: service-zuul
eureka:
  client:
    service-url:
       defaultZone: http://wangtao:123456@peer2:8762/eureka
server:
  port: 8361

#路由过滤器
zuul:
  routes:
    api-a:
        path: /api-a/**
        serviceId: service-ribbon
    api-b:
        path: /api-b/**
        serviceId: eureka-feign
---
spring:
  profiles: dev
  application:
        name: service-zuul
eureka:
  client:
    service-url:
       defaultZone: http://wangtao:123456@peer1:8761/eureka
server:
  port: 8362

#路由过滤器
zuul:
  routes:
    api-a:
        path: /api-a/**
        serviceId: service-ribbon
    api-b:
        path: /api-b/**
        serviceId: eureka-feign