spring:
  profiles:
    active: test
  application:
    name: eureka-client1
---
spring:
  profiles: test
server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/
---
spring:
  profiles: dev
server:
  port: 8764
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8761/eureka/

