spring:
  profiles:
    active: test
  application:
    name: eureka-client
---
spring:
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://wangtao:123456@peer2:8761/eureka
---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://wangtao:123456@peer2:8761/eureka
      