spring:
  profiles:
    active: test
  application:
    name: '{cipher}eafc7347e3060681e219b9914646ae17555e848b6de82c80dfb1037fea1533f8'
---
spring:
  profiles: test
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/
---
spring:
  profiles: dev
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/