spring:
  profiles:
    active: test
  application:
    name: eureka-client
---
spring:
  profiles: test
server:
  port: 8661
eureka:
  client:
    serviceUrl:
      defaultZone: http://wangtao:123456@peer2:8762/eureka
---
spring:
  profiles: test2
server:
  port: 8662
eureka:
  client:
    serviceUrl:
      defaultZone: http://wangtao:123456@peer1:8761/eureka
      